server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${dcp.datasource.driver-class-name}
    url: jdbc:mysql://${dcp.datasource.host}:${dcp.datasource.port}/${dcp.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${dcp.datasource.username}
    password: ${dcp.datasource.password}

mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  configuration:
    #??????
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        demo:
          mapper: debug
          service: info
          controller: info


